#pragma once

#include <string>

#define NUM_JOINTS_IN_HUMAN		108				// except for dummy joints

namespace Human 
{
	enum
	{
		UNDEFINED=-1,
		PELVIS=0,
		SPINE_1, SPINE_2, SPINE_3, SPINE_4, CHEST, 
		NECK, HEAD,
		RIGHT_SHOULDER, LEFT_SHOULDER,
		RIGHT_COLLAR, LEFT_COLLAR,
		UPPER_RIGHT_ARM, UPPER_LEFT_ARM, LOWER_RIGHT_ARM, LOWER_LEFT_ARM,
		UPPER_RIGHT_LEG, UPPER_LEFT_LEG, LOWER_RIGHT_LEG, LOWER_LEFT_LEG,
		RIGHT_FOOT, LEFT_FOOT, RIGHT_TOE, LEFT_TOE,
		RIGHT_PALM,
		RIGHT_FINGER_11, RIGHT_FINGER_12, RIGHT_FINGER_13,
		RIGHT_FINGER_21, RIGHT_FINGER_22, RIGHT_FINGER_23,
		RIGHT_FINGER_31, RIGHT_FINGER_32, RIGHT_FINGER_33,
		RIGHT_FINGER_41, RIGHT_FINGER_42, RIGHT_FINGER_43,
		RIGHT_FINGER_51, RIGHT_FINGER_52, RIGHT_FINGER_53,
		LEFT_PALM,
		LEFT_FINGER_11, LEFT_FINGER_12, LEFT_FINGER_13,
		LEFT_FINGER_21, LEFT_FINGER_22, LEFT_FINGER_23,
		LEFT_FINGER_31, LEFT_FINGER_32, LEFT_FINGER_33,
		LEFT_FINGER_41, LEFT_FINGER_42, LEFT_FINGER_43,
		LEFT_FINGER_51, LEFT_FINGER_52, LEFT_FINGER_53,
		RIGHT_HEEL, LEFT_HEEL,

		DUMMY_1, DUMMY_2, DUMMY_3, DUMMY_4, DUMMY_5,
		DUMMY_6, DUMMY_7, DUMMY_8, DUMMY_9, DUMMY_10,
		DUMMY_11, DUMMY_12, DUMMY_13, DUMMY_14, DUMMY_15,
		DUMMY_16, DUMMY_17, DUMMY_18, DUMMY_19, DUMMY_20,
		DUMMY_21, DUMMY_22, DUMMY_23, DUMMY_24, DUMMY_25,
		DUMMY_26, DUMMY_27, DUMMY_28, DUMMY_29, DUMMY_30,
		DUMMY_31, DUMMY_32, DUMMY_33, DUMMY_34, DUMMY_35,
		DUMMY_36, DUMMY_37, DUMMY_38, DUMMY_39, DUMMY_40,
		DUMMY_41, DUMMY_42, DUMMY_43, DUMMY_44, DUMMY_45,
		DUMMY_46, DUMMY_47, DUMMY_48, DUMMY_49, DUMMY_50,
	};

	extern int				human_symmetric_part[];
	extern std::string		human_part_name[];
	extern int				dof_for_each_part[];
};
